apiVersion: v1
kind: ConfigMap
metadata:
  name: soliferme-config
  namespace: soliferme
data:
  NODE_ENV: production
  BACKEND_PORT: "5000"
  AI_SERVICE_PORT: "5001"
  CORS_ORIGIN: "http://frontend"
  KAFKA_ENABLED: "true"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "fruitytrack-backend"
  KAFKA_TOPIC_PREFIX: "fruitytrack"
