apiVersion: v1
kind: Secret
metadata:
  name: soliferme-secrets
  namespace: soliferme
type: Opaque
stringData:
  MONGO_USER: admin
  MONGO_PASSWORD: change_me
  MONGO_DATABASE: soliferme
  JWT_SECRET: change_me
  MONGODB_URI: mongodb://admin:change_me@mongodb:27017/soliferme?authSource=admin
  AI_SERVICE_URL: http://ai-service:5001
  REACT_APP_API_URL: http://backend:5000
  SMTP_USER: change_me
  SMTP_PASSWORD: change_me
  ALERT_WEBHOOK_AUTH_HEADER: ""
